DELETE http://localhost:8080/vms/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA1MzI1OTcsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciJ9.-q1UdK4RaJDO1M2XpwBEZrzW2-AXSrPCfrB1HJoW48U
